### PR TITLE
Updating testing code

### PR DESCRIPTION
**Pull request by andrew-phillips-1**
Previously the second term could be negative and hence result in lowering of testing rate before 2009.  I hope this takes care of it ?

### CODE REVIEW

**Comment by LoveleenB-M** [comment]
Do we need 'initial_rate_1sttest' (set to zero) and the zeros here at all rate_reptest =' 0.0000' + ...

**Comment by ValentinaCambiano** [comment]
> Do we need 'initial_rate_1sttest' (set to zero) and the zeros here at all rate_reptest =' 0.0000' + ...

I do think we need initial_rate_1sttest to be set to zero. This is a new parameter, right?
I agree that the "' 0.0000'" in the "rate_reptest =' 0.0000' + ..." could be removed

**Comment by LoveleenB-M** [comment]
Initial_rate_1sttest is an old parameter which at one point was something other than zero but we changed it to zero a few years ago. It is used here:

		rate_1sttest = initial_rate_1sttest + (min(caldate{t},date_test_rate_plateau)-(date_start_testing+5.5))*an_lin_incr_test;

Since it is zero, I don't think we need it but perhaps I'm missing something.

**Comment by ValentinaCambiano** [comment]
> Initial_rate_1sttest is an old parameter which at one point was something other than zero but we changed it to zero a few years ago. It is used here:
> 
> ```
> 	rate_1sttest = initial_rate_1sttest + (min(caldate{t},date_test_rate_plateau)-(date_start_testing+5.5))*an_lin_incr_test;
> ```
> 
> Since it is zero, I don't think we need it but perhaps I'm missing something.

No, it all makes sense, agree with you!

**Comment by jennifersmith203** [comment]
I think it all makes sense to me too. We need rate_1sttest to be set to something in the period 2003.5 to 2009 so I would favour keeping initial_rate_1sttest in and set to 0 (i.e. as is suggested in the PR) rather than hard-coding the value....hope I have understood the conversation correctly! Agree the 0.0000 can be removed.

**Review by jennifersmith203 — APPROVED** [review]

**Review by ValentinaCambiano — APPROVED** [review]

**Comment by andrew-phillips-1** [comment]
Thanks.  Maybe we can confirm changes to this and approval on our call on Thursday.

**Pull request merged**
